export const styles = {
    container: {
      maxWidth: { xs: "100%", sm: "80%", md: "1100px" },
      width: "100%",
      height: "100%",
      margin: "0 auto",
      padding: "1rem 1rem 3rem 1rem",
      marginBottom: "1rem",
      borderRadius: { xs: "none", sm: "0 0 1rem 1rem" },
      boxShadow: {
        xs: "none",
        sm: "rgba(0,0,0, 0.5) 0px 10px 15px -3px, rgba(0,0,0, 0.5) 0px 4px 6px -2px",
      },
      background: "rgba(255, 255, 255, 0.1)",
      backdropFilter: "blur(8px)",
      border: "1px solid rgba(255, 255, 255, 0.2)",
    },
    header: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      width: "100%",
      marginBottom: "1rem",
    },
    logo: {
      height: "50px",
      width: "50px",
      objectFit: "contain",
    },
    linkedInLink: { display: "flex" },
   linkedInIcon: {
      fontSize: { xs: "26px", sm: "26px", md: "26px" },
      color: "white",
      "&:hover": { color: "#2d95bd" },
    },
    loadingBox: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      width: "100%",
      minHeight: "500px",
    },
    loadingText: {
      fontSize: { xs: "10px", sm: "12px" },
      color: "rgba(255, 255, 255, .8)",
      lineHeight: 1,
      fontFamily: "Poppins",
    },
    welcomeBox: {
      xs: 12,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      width: "100%",
      minHeight: "500px",
    },
    splashIcon: {
      fontSize: { xs: "100px", sm: "120px", md: "150px" },
    },
    welcomeText: {
      fontSize: { xs: "12px", sm: "14px" },
      color: "rgba(255,255,255, .85)",
      fontFamily: "Poppins",
      textAlign: "center",
      margin: "2rem 0",
      maxWidth: "80%",
      lineHeight: "22px",
    },
  };